import test from"node:test";
import assert from"node:assert/strict";
import{readFile}from"node:fs/promises";
import path from"node:path";
import{handleRequest}from"../src/entry.js";
const mime={".html":"text/html; charset=utf-8",".json":"application/json; charset=utf-8",".css":"text/css; charset=utf-8",".js":"text/javascript; charset=utf-8",".svg":"image/svg+xml"};
function createEnv(){return{PUBLIC_ORIGIN:"https://web.claryel.space",FREE_SITE_LIMIT:"2",PRODUCT_VERSION:"0.3.0",ASSETS:{async fetch(request){const url=new URL(request.url);let pathname=url.pathname;if(pathname==="/")pathname="/index.html";const file=path.join(process.cwd(),"public",pathname.replace(/^\//,""));try{return new Response(await readFile(file),{headers:{"Content-Type":mime[path.extname(file)]||"application/octet-stream"}});}catch{return new Response("not found",{status:404});}}}};}
test("health reports 0.3.0",async()=>{const response=await handleRequest(new Request("https://web.claryel.space/api/health"),createEnv());assert.equal(response.status,200);assert.equal((await response.json()).version,"0.3.0");});
test("public config is account based and exposes the exact twenty-language contract",async()=>{const body=await(await handleRequest(new Request("https://web.claryel.space/api/public-config"),createEnv())).json();assert.equal(body.freeSiteLimit,2);assert.equal(body.freeLimitBasis,"account-holder");assert.equal(body.localePaths.it,"/it/");assert.equal(body.publicLocales.length,20);assert.equal(body.publicLocales.includes("ru"),true);assert.equal(body.publicLocales.includes("ar"),true);assert.deepEqual(body.hiddenLocales,[]);assert.equal(body.universeUrl,"https://claryel.space/universe/");});
test("legacy language query redirects to canonical path",async()=>{const response=await handleRequest(new Request("https://web.claryel.space/?lang=it"),createEnv());assert.equal(response.status,308);assert.equal(response.headers.get("location"),"https://web.claryel.space/it/");});
test("locale path receives server-rendered metadata and shared controls",async()=>{const response=await handleRequest(new Request("https://web.claryel.space/it/"),createEnv());const html=await response.text();assert.equal(response.status,200);assert.equal(response.headers.get("Content-Language"),"it-IT");assert.match(html,/lang="it-IT"/);assert.match(html,/href="https:\/\/web\.claryel\.space\/it\/"/);assert.match(html,/CLARYEL Web Community — Crea e gestisci siti con la voce/);assert.match(html,/claryel-standard\.css\?v=1\.0\.0/);assert.match(html,/claryel-standard\.js\?v=1\.0\.0/);});
test("Russian path is public and indexable",async()=>{const response=await handleRequest(new Request("https://web.claryel.space/ru/"),createEnv());assert.equal(response.headers.get("X-Robots-Tag"),null);assert.equal(response.headers.get("Content-Language"),"ru-RU");const html=await response.text();assert.match(html,/lang="ru-RU"/);assert.match(html,/data-hidden-locale="false"/);assert.match(html,/index,follow,max-image-preview:large/);});
test("Arabic path is public and RTL",async()=>{const response=await handleRequest(new Request("https://web.claryel.space/ar/"),createEnv());assert.equal(response.headers.get("Content-Language"),"ar-SA");const html=await response.text();assert.match(html,/<html lang="ar-SA" dir="rtl"/);assert.match(html,/data-hidden-locale="false"/);});
test("sitemap uses all twenty canonical locale paths",async()=>{const text=await(await handleRequest(new Request("https://web.claryel.space/sitemap.xml"),createEnv())).text();assert.equal((text.match(/<url>/g)||[]).length,20);assert.match(text,/https:\/\/web\.claryel\.space\/it\//);assert.match(text,/https:\/\/web\.claryel\.space\/hi\//);assert.match(text,/https:\/\/web\.claryel\.space\/ar\//);assert.match(text,/https:\/\/web\.claryel\.space\/id\//);assert.match(text,/https:\/\/web\.claryel\.space\/uk\//);assert.match(text,/https:\/\/web\.claryel\.space\/ru\//);assert.doesNotMatch(text,/\?lang=/);});
test("voice permission is enabled only for self",async()=>{const response=await handleRequest(new Request("https://web.claryel.space/"),createEnv());assert.equal(response.headers.get("Permissions-Policy"),"camera=(), microphone=(self), geolocation=(), payment=()");});
test("state-changing requests are rejected",async()=>{const response=await handleRequest(new Request("https://web.claryel.space/api/health",{method:"POST"}),createEnv());assert.equal(response.status,405);});
