import test from"node:test";
import assert from"node:assert/strict";
import{readFile}from"node:fs/promises";
import path from"node:path";
import{handleRequest}from"../src/entry.js";
const mime={".html":"text/html; charset=utf-8",".json":"application/json; charset=utf-8",".css":"text/css; charset=utf-8",".js":"text/javascript; charset=utf-8",".svg":"image/svg+xml"};
const localeMeta={en:["en-GB","ltr"],it:["it-IT","ltr"],ar:["ar-SA","rtl"],ru:["ru-RU","ltr"]};
function boxDocument(pathname){const segment=pathname.split("/").filter(Boolean)[0]||"en";const code=segment==="zh-cn"?"zh-CN":segment;const[language,direction]=localeMeta[code]||[code,"ltr"];return`<!doctype html><html lang="${language}"${direction==="rtl"?' dir="rtl"':''} data-site="box" data-locale="${code}"><head><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="https://claryel.com${pathname}"></head><body><canvas id="heroCanvas"></canvas><script src="/sites/box/assets/production-v11.js"></script></body></html>`;}
function createEnv(){return{PUBLIC_ORIGIN:"https://web.claryel.space",BOX_ORIGIN:"https://claryel.com",FREE_SITE_LIMIT:"2",PRODUCT_VERSION:"0.4.0",BOX_FETCH:async request=>{const pathname=new URL(request.url).pathname;if(pathname.includes("."))return new Response("box asset",{headers:{"Content-Type":"text/javascript; charset=utf-8"}});return new Response(boxDocument(pathname),{headers:{"Content-Type":"text/html; charset=utf-8","Content-Security-Policy":"default-src 'self'"}});},ASSETS:{async fetch(request){const url=new URL(request.url);let pathname=url.pathname;if(pathname==="/")pathname="/index.html";const file=path.join(process.cwd(),"public",pathname.replace(/^\//,""));try{return new Response(await readFile(file),{headers:{"Content-Type":mime[path.extname(file)]||"application/octet-stream"}});}catch{return new Response("not found",{status:404});}}}};}
test("health reports 0.4.0 and the preserved route",async()=>{const response=await handleRequest(new Request("https://web.claryel.space/api/health"),createEnv());assert.equal(response.status,200);const body=await response.json();assert.equal(body.version,"0.4.0");assert.equal(body.preservedPath,"/classic/");assert.equal(body.landingSource,"https://claryel.com");});
test("public config is account based and exposes the exact twenty-language contract",async()=>{const body=await(await handleRequest(new Request("https://web.claryel.space/api/public-config"),createEnv())).json();assert.equal(body.freeSiteLimit,2);assert.equal(body.freeLimitBasis,"account-holder");assert.equal(body.localePaths.it,"/it/");assert.equal(body.publicLocales.length,20);assert.equal(body.publicLocales.includes("ru"),true);assert.equal(body.publicLocales.includes("ar"),true);assert.deepEqual(body.hiddenLocales,[]);assert.equal(body.universeUrl,"https://claryel.space/universe/");assert.equal(body.preservedPath,"/classic/");});
test("legacy language query redirects to canonical Box path",async()=>{const response=await handleRequest(new Request("https://web.claryel.space/?lang=it"),createEnv());assert.equal(response.status,308);assert.equal(response.headers.get("location"),"https://web.claryel.space/it/");});
test("locale root receives the exact proxied Box document",async()=>{const response=await handleRequest(new Request("https://web.claryel.space/it/"),createEnv());const html=await response.text();assert.equal(response.status,200);assert.equal(response.headers.get("Content-Language"),"it-IT");assert.equal(response.headers.get("Content-Security-Policy"),"default-src 'self'");assert.match(html,/lang="it-IT"/);assert.match(html,/data-site="box"/);assert.match(html,/data-community-proxy="box-baseline"/);assert.match(html,/href="https:\/\/web\.claryel\.space\/it\/"/);assert.match(html,/\/sites\/box\/assets\/production-v11\.js/);});
test("Russian Box path is public and indexable",async()=>{const response=await handleRequest(new Request("https://web.claryel.space/ru/"),createEnv());assert.equal(response.headers.get("X-Robots-Tag"),null);assert.equal(response.headers.get("Content-Language"),"ru-RU");const html=await response.text();assert.match(html,/lang="ru-RU"/);assert.match(html,/data-locale="ru"/);assert.match(html,/index,follow,max-image-preview:large/);});
test("Arabic Box path is public and RTL",async()=>{const response=await handleRequest(new Request("https://web.claryel.space/ar/"),createEnv());assert.equal(response.headers.get("Content-Language"),"ar-SA");const html=await response.text();assert.match(html,/<html lang="ar-SA" dir="rtl"/);assert.match(html,/data-community-proxy="box-baseline"/);});
test("preserved localized Community path receives its original metadata and shared controls",async()=>{const response=await handleRequest(new Request("https://web.claryel.space/it/classic/"),createEnv());const html=await response.text();assert.equal(response.status,200);assert.equal(response.headers.get("Content-Language"),"it-IT");assert.match(html,/data-site="community" data-locale="it"/);assert.match(html,/data-preserved-route="classic"/);assert.match(html,/href="https:\/\/web\.claryel\.space\/it\/classic\/"/);assert.match(html,/CLARYEL Web Community — Crea e gestisci siti con la voce/);assert.match(html,/claryel-standard\.css\?v=1\.0\.0/);assert.match(html,/claryel-standard\.js\?v=1\.0\.0/);});
test("sitemap uses all twenty canonical Box locale paths",async()=>{const text=await(await handleRequest(new Request("https://web.claryel.space/sitemap.xml"),createEnv())).text();assert.equal((text.match(/<url>/g)||[]).length,20);assert.match(text,/https:\/\/web\.claryel\.space\/it\//);assert.match(text,/https:\/\/web\.claryel\.space\/hi\//);assert.match(text,/https:\/\/web\.claryel\.space\/ar\//);assert.match(text,/https:\/\/web\.claryel\.space\/id\//);assert.match(text,/https:\/\/web\.claryel\.space\/uk\//);assert.match(text,/https:\/\/web\.claryel\.space\/ru\//);assert.doesNotMatch(text,/classic/);assert.doesNotMatch(text,/\?lang=/);});
test("voice permission remains enabled only on the preserved Community application",async()=>{const response=await handleRequest(new Request("https://web.claryel.space/classic/"),createEnv());assert.equal(response.headers.get("Permissions-Policy"),"camera=(), microphone=(self), geolocation=(), payment=()");});
test("Box assets are proxied without upstream cookies",async()=>{let cookie=null;const env=createEnv();env.BOX_FETCH=async request=>{cookie=request.headers.get("Cookie");return new Response("asset",{headers:{"Content-Type":"text/javascript","Set-Cookie":"upstream=forbidden"}});};const response=await handleRequest(new Request("https://web.claryel.space/sites/box/assets/production-v11.js",{headers:{Cookie:"community=private"}}),env);assert.equal(response.status,200);assert.equal(cookie,null);assert.equal(response.headers.get("Set-Cookie"),null);assert.equal(await response.text(),"asset");});
test("state-changing requests are rejected",async()=>{const response=await handleRequest(new Request("https://web.claryel.space/api/health",{method:"POST"}),createEnv());assert.equal(response.status,405);});
